name: Build Desktop Apps

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            artifact_name: HebrewDatesDemo-macOS
            archive_cmd: |
              cd dist
              zip -r "../HebrewDatesDemo-${VERSION}-macOS.zip" "HebrewDatesDemo.app"

          - os: ubuntu-latest
            artifact_name: HebrewDatesDemo-linux
            archive_cmd: |
              cd dist
              tar -czf "../HebrewDatesDemo-${VERSION}-linux.tar.gz" HebrewDatesDemo

          - os: windows-latest
            artifact_name: HebrewDatesDemo-windows
            archive_cmd: |
              powershell Compress-Archive -Path dist/HebrewDatesDemo/* -DestinationPath HebrewDatesDemo-${env:VERSION}-windows.zip

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version from git tag
        shell: bash
        run: |
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pyinstaller

      - name: Build app (macOS/Linux)
        if: runner.os != 'Windows'
        run: |
          pyinstaller \
            --noconfirm \
            --clean \
            --windowed \
            --name "HebrewDatesDemo" \
            --collect-all tkcalendar \
            --hidden-import babel.numbers \
            --icon=assets/icon.png \
            --add-data="assets:assets" \
            main.py

      - name: Build app (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller `
            --noconfirm `
            --clean `
            --windowed `
            --name "HebrewDatesDemo" `
            --collect-all tkcalendar `
            --hidden-import babel.numbers `
            --icon=assets/icon.ico `
            --add-data "assets;assets" `
            main.py

      - name: Package artifact
        run: ${{ matrix.archive_cmd }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            *.zip
            *.tar.gz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip
            *.tar.gz
